language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -e . --quiet
jobs:
  include:
    - script: ./tests/end2end_pytorch/run.sh
    - script: ./tests/end2end_tensorflow/run.sh
    - script: ./tests/test_docs/run.sh
